AWSTemplateFormatVersion: '2010-09-09'
Description: Mozilla federated Admin ReadOnly and ViewOnly IAM roles for the mozilla-iam AWS account
Metadata:
  Source: https://github.com/mozilla-iam/cloudformation-templates/tree/master/federated-iam-roles/oidc_federated_roles.yaml
Resources:
  AdminIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-Admin
      Description: !Join [ '', [ 'AdministratorAccess Federated IAM Role which the group team_opsec is permitted to assume']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - aws_320464205386_admin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 43200  # 12 hours
  ReadOnlyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-ReadOnly
      Description: !Join [ '', [ 'ReadOnlyAccess Federated IAM Role which the group team_opsec and mozilliansorg_infosec-prod-florian-temp-read is permitted to assume. This Role enables viewing sensitive data like S3 file contents, DynamoDB table contents, etc']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - aws_320464205386_read_only
                  - aws_320464205386_admin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      MaxSessionDuration: 43200  # 12 hours
  ViewOnlyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-ViewOnly
      Description: !Join [ '', [ 'ViewOnlyAccess Federated IAM Role which the group team_opsec is permitted to assume. This Role enables viewing only resource metadata, not sensitive data like S3 file contents']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - aws_320464205386_read_only
                  - aws_320464205386_admin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      MaxSessionDuration: 43200  # 12 hours
